# SPDX-License-Identifier: GPL-2.0
#
# Copyright (C) Microsoft Corporation. All rights reserved.
#
# Makefile for building the properties that IPE uses
# as part of the kernel tree.
#

obj-$(CONFIG_SECURITY_IPE) += properties.o

properties-$(CONFIG_IPE_BOOT_PROP) += boot-verified.o
properties-$(CONFIG_IPE_DM_VERITY_SIGNATURE) += dmverity-signature.o
properties-$(CONFIG_IPE_DM_VERITY_ROOTHASH) += dmverity-roothash.o
properties-$(CONFIG_IPE_INTENDED_PATHNAME) += intended-pathname.o
